version: 2.1

dependencies:
  pre:

jobs:
  build:

    docker:
      - image: quay.io/fenicsproject/stable:2019.1.0.r3
        user: fenics
        environment:
          LD_LIBRARY_PATH: /home/fenics/local/lib
          CMAKE_PREFIX_PATH: /home/fenics/local
    working_directory: /home/fenics/xalpost

    steps:
      - checkout

      - run:
          name: install-python-requirements
          command: |
            python3 -m pip install --upgrade pip --user
            python3 -m pip install pytest --upgrade --user
            python3 -m pip install pytest-xdist --user
            python3 -m pip install git+git://github.com/jakobes/xalode --user

      - run:
          name: Environment and FEniCS version info
          command: |
            echo $USER $HOME $PWD $PATH $LD_LIBRARY_PATH $CMAKE_PREFIX_PATH
            python3 -c "import ffc; print(ffc.git_commit_hash(), ffc.ufc_signature())"
            python3 -c "import dolfin; print(dolfin.git_commit_hash())"

      - run:
          name: Install xalpost
          command: |
            python3 -m pip install git+git://github.com/mikaem/fenicstools --user
            python3 -m pip install cppimport --user
            python3 -c "import fenicstools; fenicstools.Probe"
            python3 -m pip install . --user

      - run:
          name: Import xalbrain first time (JIT)
          command: |
            python3 -c "import h5py; import post"

      - run:
          name: Unit tests
          command: |
              python3 -m pytest -v -n 4 tests/unit
 
      - run:
          name: Integration tests
          command: |
              python3 -m pytest -v -n 1 tests/integration
